# =========================
# SERVER CONFIGURATION
# =========================

server1.url = http://192.168.51.140:8117/sol/login
server1.username = innoweb.demo
server1.password = Inno#123

server2.url = https://www.shipmentonline.co/efl/login
server2.username = innoweb.efl
server2.password = Inno#123

server3.url = https://www.shipmentonline.co/aps/login
server3.username = innoweb.aps
server3.password = Inno#123

server4.url = https://www.shipmentonline.co/osl/login
server4.username = innoweb.osl
server4.password = Inno#123

server5.url = https://www.shipmentonline.co/jdl/login
server5.username = innoweb.jdl
server5.password = Inno#123


browser = chrome
