#app.url = http://192.168.51.140:8117/sol/login
#app.username = innoweb.demo
#app.password = Inno#123

#app.url = https://www.shipmentonline.co/efl/login
#app.username = innoweb.efl
#app.password = Inno#123
#
#app.url = https://www.shipmentonline.co/aps/login
#app.username = innoweb.aps
#app.password = Inno#123
#
#app.url = https://www.shipmentonline.co/osl/login
#app.username = innoweb.osl
#app.password = Inno#123
#
#app.url = https://www.shipmentonline.co/jdl/login
#app.username = innoweb.jdl
#app.password = Inno#123


browser = chrome